### ISSUE TITLE
(Tamil Version) Image content must be shown in Tamil.

### ISSUE THREAD

**Issue by Hemanath78** [fssa-batch3/balaji.saravanan__web_project#10]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGEwZDVjNGEtOThmMC00OTk1LTk2ZjgtOGU4NzNlZTdlNTUyIiwiZGVwbG95X2lkIjoiNjQ1MGQ5MjMwMWIzYWEwMDA4ZGMxNzgyIiwiaWQiOiI5MDY3OGQ4Ni1mM2IzLTQwZjctOWMzNC1mMWI2OTY0ZTMwMjkifQ==)

### Description of issue
- The above images showing English text in the Tamil version.

### Expected result
- The image contents must be shown in Tamil.

### Actual result
- It's showing in English

### Steps to reproduce
1. Navigate to home page of the website.
2. You can find the above image.

```
Path:      /
Browser:   Edge 112.0.1722.64 on Windows 10
Viewport:  1447 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--politifact.netlify.app%2F&os=Windows&os_version=10&browser=Edge&browser_version=112.0&resolution=1447x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--politifact.netlify.app/)

**Comment by balajis5531** [comment]
issue solved
