### ISSUE TITLE
(Tamil Version) Parties profile showing English party name in Tamil version.

### ISSUE THREAD

**Issue by Hemanath78** [fssa-batch3/balaji.saravanan__web_project#13]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGEwZDVjNGEtOThmMC00OTk1LTk2ZjgtOGU4NzNlZTdlNTUyIiwiZGVwbG95X2lkIjoiNjQ1MGQ5MjMwMWIzYWEwMDA4ZGMxNzgyIiwiaWQiOiI2ZGY1MzRlMS0yYjUxLTQzZDMtOTM2Yy05NjczZDc3N2ViNjYifQ==)

### Description of issue
- In the parties-profile page there are four parties available for the four parties English party name is showing in the Tamil version.

### Expected result
- Only Tamil party name must be show.

### Actual result
- Showing both Tamil and English names.

### Steps to reproduce
1. Navigate to the parties' profile page.
2. In that page there are four parties' profile.
3. You can see both language name Tamil and English.

```
Path:      /pages/portfolio/parties-profile.html
Browser:   Edge 112.0.1722.64 on Windows 10
Viewport:  1447 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--politifact.netlify.app%2Fpages%2Fportfolio%2Fparties-profile.html&os=Windows&os_version=10&browser=Edge&browser_version=112.0&resolution=1447x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--politifact.netlify.app/pages/portfolio/parties-profile.html)

**Comment by balajis5531** [comment]
issue solved.
