### ISSUE TITLE
Form number input valitation

### ISSUE THREAD

**Issue by yogeshwari-selvendran** [fssa-batch3/balaji.saravanan__web_project#5]
### Description of issue
Form input valitation

### Expected result
Mobile number input should not accept the alphabet,  and minimum 10 character length.

### Actual result
Mobile number input  accept the alphabet,

### Steps to reproduce
1. In mobile number input field type the text
2. Click the submit button
3. You navigate to the signin page

```
Path:      /pages/register.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--politifact.netlify.app%2Fpages%2Fregister.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--politifact.netlify.app/pages/register.html)

**Comment by balajis5531** [comment]
I fix the bug
