### ISSUE TITLE
Minimum character length

### ISSUE THREAD

**Issue by yogeshwari-selvendran** [fssa-batch3/balaji.saravanan__web_project#6]
### Description of issue
Name input field Minimum character 

### Expected result
Name input field minimum length 3 character.  

### Actual result
Name input field minimum length 6 character.

### Steps to reproduce
1. In name input field type the four character name, Ex: sasi, bala
2. The input field should not accept the minimum 4 character name
3.  

```
Path:      /pages/register.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--politifact.netlify.app%2Fpages%2Fregister.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--politifact.netlify.app/pages/register.html)

**Comment by balajis5531** [comment]
I fix the bug
