### ISSUE TITLE
(Tamil Version) Nav bar all the contents are not in Tamil language.

### ISSUE THREAD

**Issue by Hemanath78** [fssa-batch3/balaji.saravanan__web_project#8]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGEwZDVjNGEtOThmMC00OTk1LTk2ZjgtOGU4NzNlZTdlNTUyIiwiZGVwbG95X2lkIjoiNjQ1MGQ5MjMwMWIzYWEwMDA4ZGMxNzgyIiwiaWQiOiI3YzhiYzBjZC00YTJjLTRkNTgtYjU5OC0zODJkOTc1MDEwMGMifQ==)

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiNGEwZDVjNGEtOThmMC00OTk1LTk2ZjgtOGU4NzNlZTdlNTUyIiwiZGVwbG95X2lkIjoiNjQ1MGQ5MjMwMWIzYWEwMDA4ZGMxNzgyIiwiaWQiOiIyYTg2MTM3Zi0zMzNiLTQ5ZjgtYjMxYi0yMDg4Y2UwYmZmOGMifQ==)

### Description of issue
Browsing the website in Tamil 
- In the header of the webpage there is two options
- One is language
   - The language is in English.
   - And their options also in English.
- Another one option is ulnulaga
  - It is having two options one is login and another one is sign up it is showing both in English.

### Expected result
- In Tamil version all the contents must be show in Tamil

### Actual result
- Not showing in Tamil.

### Steps to reproduce
1. Navigate too the home page.
2. Browse the header the website.
3. You can find the above two options.

```
Path:      /
Browser:   Edge 112.0.1722.64 on Windows 10
Viewport:  1447 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--politifact.netlify.app%2F&os=Windows&os_version=10&browser=Edge&browser_version=112.0&resolution=1447x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--politifact.netlify.app/)

**Comment by balajis5531** [comment]
issue solved.
